[project]
name = "gclear"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pillow>=12.0.0",
    "pyobjc-framework-quartz>=12.1",
    "pyqt6>=6.10.0",
    "roboflow>=1.2.11",
    "ultralytics>=8.3.233",
]
